### PR TITLE
Disable warning for "out of range" enum assignments

### PR DESCRIPTION
**Pull request by JeremyAgost**
Security framework specifies flag arguments that aren't declared as options for the flag type so these warnings are spurious.

### CODE REVIEW

**Comment by zorgiepoo** [comment]
Where in Sparkle's code does this warning fire off?

To sidestep the warning, when you really need to, isn't it more ideal to use a typecast to the enum type?

**Comment by jakepetroules** [comment]
Pretty sure I already properly fixed those warnings. What Xcode are you using?

**Comment by JeremyAgost** [comment]
Typecast to the appropriate enum type isn't possible because the Security headers are poorly written and the flag argument is frequently a different type then the valid flags are defined as.

You may have fixed it already, I think I was inadvertently basing off an earlier revision. I'll check against your master.

**Comment by pornel** [comment]
I think it was fixed alredy

**Pull request closed without merging**
