### PR TITLE
Fix pt_BR translations

### PR DESCRIPTION
**Pull request by fujisoft**
"Translation Error Correction"
It must have a faithful consistency to the translation terminologies of Apple Inc.

### CODE REVIEW

**Comment by pornel** [comment]
Thank you

**Comment by vitu** [comment]
Sorry to say, but these should be reverted (as well as #1039). If one consults Apple's glossaries, it's clear that suggestions by fujisoft are off – and worse, the justification used is false.

Some examples from Apple's glossary:
**Would you like** to replace it? = **Deseja** substituí-la?
**Would you like** to merge these duplicate cards? = **Deseja** combinar estes cartões duplicados?
**Would you like** to run First Aid on “%@”? = **Deseja** executar o Reparador em “%@”?

Please quit and **relaunch** Photos and try again. = Encerre o Fotos, **reabra**-o e tente novamente.
Please wait while it finishes or Quit Dictionary and **relaunch** it later. = Aguarde a conclusão ou encerre o Dicionário e **reabra**-o mais tarde.
**Quit** and relaunch Photos and try again. = Encerre o Fotos, **reabra**-o e tente novamente.</seg>

**Archive** = **Arquivo Comprimido**
Create **Archive** = Criar **Arquivo Comprimido**
into same directory as **archive** = no mesmo diretório do **arquivo comprimido**

Add **Feed** = Adicionar **Feed**
Convert Cocoa URL to RSS **Feed** = Converter URL Cocoa em **Feed** RSS
**Feed** Title = Título do **Feed**

**Check** for updates = **Buscar** atualizações
**Check** for Updates Automatically = **Buscar** Atualizações Automaticamente
Automatically check for updates = **Buscar** atualizações automaticamente

As you can see from the examples above, the suggested changes are definitely not in tandem with Apple's terminology, glossary or style.

Please let me know.

**Comment by pornel** [comment]
OK, I've reverted these commits. Sadly, I don't know Portuguese, so I can't tell which version is better.

@fujisoft do you have any comments?

**Comment by fujisoft** [comment]
Sorry for not responding sooner.
I have no idea which is the best. We know Apple itself has translations into Portuguese that are completely out of vocabulary.
I do not want to do an edit war here. So we will make a private fork for keeping our favorites.

**Comment by pornel** [comment]
OK. In general we prefer to use the same terminology as Apple.

If Apple's translation is poor, please file a bug with Apple. When they fix it, we'll follow :)

**Pull request merged**
