### PR TITLE
For Debug builds, disabling timestamps in code signing means the buil…

### PR DESCRIPTION
**Pull request by danielpunkass**
…ds can take place without a network connection.

### CODE REVIEW

**Comment by jakepetroules** [comment]
Smart!

**Comment by zorgiepoo** [comment]
I highly am against this. Sparkle shouldn't be built and code signed at once first off (it should be dragged in an application target and code signed on copy). And what if someone does try to sign a debug build and use it somewhere if even by accident? The time stamp is important. If you really want to be building without an Internet connection you should either not be signing at all or be using a self signed certificate.

**Comment by danielpunkass** [comment]
@zorgiepoo Since as you say it's relatively unlikely that any shipping app would not re-sign the framework anyway, it only seems to diminish the importance of jumping through hoops to make sure the signature (especially for a Debug build) is perfect.

For my purposes it would serve the same purpose to turn off code signing all together on Debug builds, but my philosophy has usually been that it's a good idea to maintain as close a parity between Release and Debug as reasonably possible.

I have used this trick of disabling timestamp support for Debug builds for a long time and never paid a price for it. It's not just a pain when you're not online for whatever reason, it also leaves you prone to surprise failures when Apple's service happens to be down or slow. I wrote more about this here FWIW if anybody is interested. http://indiestack.com/2014/01/timestamp-disservice/

**Comment by zorgiepoo** [comment]
Valid point that this is less severe in the common case if the framework is re-signed, but still not something that should be completely ruled out.

More importantly, why should Sparkle, a framework, which is supposed to be left unsigned in an application's repo, include details about code signing? On the one-time cirumstance someone needs to sign the framework from *this* project, why should we risk disabling the time stamp?

I maintain an open source project and the way I get around it is by using a self signed certificate. Other apps like Textual do it this way too. The advantage is that it doesn't require someone to pay a $100 fee to Apple, though it is a little more set up. However does not have the close parity you mention.

**Comment by danielpunkass** [comment]
I guess this comes down to how serious a risk people feel it is that a signed "Debug" copy of the framework could be distributed. I don't understand well enough how the the timestamp ties an app to its certificate, and what the realistic consequences of shipping something with that "flawed" signature would be.

It seems to me that if somebody is shipping a Debug copy of Sparkle, AND not re-signing the binary in their final app, then they have other problems than we can help them wtih by reversing this commit ;)

I'm happy to keep the change in my own fork of Sparkle though, if others share @zorgiepoo's concern. It's supremely easy to merge, I just thought I would share it as a convenience to others using the project.

**Comment by zorgiepoo** [comment]
The implications of disabling time stamp are described here (great read): http://lists.apple.com/archives/apple-cdsa/2013/Mar/msg00018.html

I worry about the situation where someone builds/signs a debug version of Sparkle and uses it in their custom build environment without knowing (And not unlikely, building debug is easier in termed of Xcode UX).

As the engineer states, this is a question of permanence not build type. I don't think we should be giving off that you shouldn't distribute such builds. They state it is our call to make whether it is a risk or not, and I personally think we shouldn't risk it, not as a library author.

**Comment by danielpunkass** [comment]
Thanks for the link. That does indeed make a concise explanation of the reason for the timestamp and the risks of omitting it.

Botton line for others following along: a built Sparkle framework signed --timestamp=none will carry its code signature and be treated as trusted by code signing validation so long as the certificate (Developer ID) used to sign it does not become compromised and then invalidated by Apple. Using the timestamp gives Apple the information needed to permanently trust your code based on its age, even if the identity is later compromised.

Personally I still don't think it's a big deal to generate less permanent/failsafe code signatures on Debug builds of Sparkle, but I can see where @zorgiepoo is coming from with his concern.

**Comment by pornel** [comment]
@zorgiepoo The e-mail you quoted contains

> Every signature that does not have such a timestamp will become invalid upon revocation.

As far as I understand that means it fails closed. If you don't timestamp and then revoke, then the non-timestamp build is revoked too.

So I don't see a problem with this.

**Comment by zorgiepoo** [comment]
To my understanding, the point of the timestamp is to ensure that your builds before your certificate was revoked are still valid.

They mention the case if it's compromised by somebody else, but do we really want to guess what may happen when a developer stops paying for their certificate or when they (forget to) renew it? It's possible their builds may be invalid and that's not a good thing.

The decision to disable timestamp is up to the developer. So my opinion is we should respect Xcode's defaults and not disable it as a framework distributor.

**Comment by zorgiepoo** [comment]
By the way, I would be pretty curious to learn why you aren't able to use the "Code Sign on Copy" feature @danielpunkass

**Comment by danielpunkass** [comment]
It's been a while since I tried to use Code Sign on Copy. My memory is it had to do with not being able to fine-tune the settings for how some items get code signed. This is particularly important when you are piecing together libraries from different projects where maybe you don't want to or can't adjust the settings in the project itself

**Comment by zorgiepoo** [comment]
Ok. All I can do is take your word for it. You may also be interested in issue #546 too (which is not easily fixable at the moment for the project as a whole). I think if there are real issues with code signing, we should continue file rdar's to Apple... Sigh.

Regardless, I still think it should be the responsibility of the application developer to specify how they may want to sign libraries they include.

Also, I hesitate to associate "Debug" with "should (or should not) be used this way." Again, what a debug build means may depend on the developer, as it did with you when you decided to turn on code signing.

Re-reading from the mailing list, you notice that Perry (who implemented code signing) makes no connection to debug builds either: 

> > Indeed, --timestamp=none is my workaround.  But I leave this setting *permanently* for *Debug* builds.  Is there any reason why I would ever need a codesigned timestamp in a Debug build?

> It's really not a question of build type. It's a question of permanence...

> > But I wonder why a default project in Xcode is not configured with --timestamp=none in Debug.  Seems like an obvious solution to me.

> Xcode can't know what you're going to do with the output, and it won't make these decisions for you. It errs on the side of caution

And so I believe we too should err on the side of caution, and not cause potential surprises going against Xcode's default.

**Comment by danielpunkass** [comment]
Ahhhhhh. This explains a lot: I assumed that Code Signing was enabled by default in Sparkle. I submitted the Debug-only code signing flags to alleviate what I perceived as a dependency Sparkle had on the timestamp service.

Looking more closely now I see that code signing was on for the Debug build of my fork as a historical artifact. I tend to agree that as long as we don't need to code sign in the library (e.g. to support entitlements or something) then it also doesn't make sense to specify built-in code signing flags.

I'm going to create a new pull request to revert the changes and recommend we do that.

Thanks for talking through this. I didn't get you were approaching this from the beginning as being something I was opting (knowingly) into doing.

**Comment by zorgiepoo** [comment]
> Thanks for talking through this. I didn't get you were approaching this from the beginning as being something I was opting (knowingly) into doing.

No problem, but even if code signing was enabled by default, I probably would have had the same stance with regards to the timestamp service ;). Typically framework authors should try to avoid code signing if they can, especially if they can be used in non-code signed projects, which Sparkle still can be. 

It's totally possible in the future there may be some opt-in code-signing required features which could complicate matters further.. we'll see.

**Pull request merged**
