### PR TITLE
Argument Parser and Swift 5

### PR DESCRIPTION
**Pull request by Wevah**
Updates various Swift tools to use Swift 5 and the [Argument Parser](https://github.com/apple/swift-argument-parser) package.

Since the tools are currently distributed without an embedded Swift runtime, users on OSs before 10.14.4 would have already needed to install the shared Swift libs.

Care is being taken to preserve the old semantics and help text as much as possible (with a few stylistic changes for consistency with Argument Parser, etc.).

(#1583)

### CODE REVIEW

**Comment by Wevah** [comment]
This unfortunately probably won't compile under Xcode 10, but the work will be done if/when the tools no longer need to build under Xcode 10.

**Comment by kornelski** [comment]
Thank you

**Comment by Wevah** [comment]
Re: Travis: It's complaining about SSH fingerprints, which is weird, since `swift-argument-parser` is on GitHub. 🤔

**Comment by Wevah** [comment]
Also, SPM-in-Xcode needs Xcode 11 (whoops).

A workaround for all of this could be to check out `swift-argument-parser` as a regular git submodule.

**Comment by Wevah** [comment]
If building on Xcode 10.3 should still be supported, I may need to revert to Swift 4.2 (though it looks like SAP should still build), but I won't know until I can fix these CI issues. 😖

**Comment by Wevah** [comment]
Switching to HTTPS for checkout of the package fixed the error there, but now some tests are failing that are completely unrelated to anything I've touched. 🤔

**Comment by kornelski** [comment]
I've restarted CI, but it consistently fails on:

> Missing package product 'ArgumentParser', please fix package resolution errors before building (in target 'generate_keys')

**Comment by Wevah** [comment]
> I've restarted CI, but it consistently fails on:
> 
> > Missing package product 'ArgumentParser', please fix package resolution errors before building (in target 'generate_keys')

Is this in the 10.3 build or 11.5?

**Comment by Wevah** [comment]
The issue might be that Xcode 10 doesn't have built-in support for SPM. I'll look at other options (old-fashioned git submodule might work).

**Comment by zorgiepoo** [comment]
We don't use travis now and this PR should be rebased before being further reviewed. We also bumped the Xcode version to at least 11 in CI (the repo ReadMe was updated regarding the policy change for what versions should be supported further onwards). Another recent policy change we made is that changes such as this one will also need to land in 2.x branch first.

**Comment by zorgiepoo** [comment]
I used the generate_keys changes here as a reference when implementing #1730 so this was quite useful to look at. I didn't write a way, like here, to use another/newly created keychain however because I wanted to still use the login keychain and didn't want to have to unlock other keychains. My rationale is if we use the login keychain to store the data, we should also be able to import to there. Maybe having another option to use a custom keychain still has its own use case too. (Also generate_keys is unfortunately pretty out of date in the master branch which important enough for me to address).

**Comment by Wevah** [comment]
I haven't touched this in a while, but IIRC the export option was just to move it from the login keychain to a separate keychain (maybe that's what you said; my brain is a bit fried).

Agreed about being able to import back to the login keychain.

**Comment by zorgiepoo** [comment]
I just noticed 2.x has been using Swift 5 for some while now (not sure when). Adopting Argument Parser (this is welcome) and using a separate keychain (if people still want that since you can import to login keychain now) need to be in separate PR's. Closing due to staleness.

**Pull request closed without merging**
