### PR TITLE
Use bundle URLs

### PR DESCRIPTION
**Pull request by pornel**
Use bundle URLs instead of paths to avoid creation of temp bundle objects

### CODE REVIEW

**Comment by pornel** [comment]
I hope this change doesn't touch Swift tests, because they need syntax changes in the latest xcode :)

**Comment by zorgiepoo** [comment]
Good idea. `SUCodeSigningVerifierTest.m` has a lot of mismatched paths/url code (eg: naming a variable a URL and assigning it a NSString, or invoking URL method on a NSString). I'm guessing it's probably why the tests are failing. Other than that I think it looks good. Don't think swift is involved here.

**Comment by zorgiepoo** [comment]
You can use -[NSURL checkResourceIsReachableAndReturnError:] instead of -[NSFileManager fileExistsAtPath:] to remove the nullability warnings in SUCodeSigningVerifier.m

**Comment by pornel** [comment]
Thanks. I didn't know it existed.

**Pull request merged**
