### PR TITLE
update some russian translates

### PR DESCRIPTION
**Pull request by sc0rp10**
## Checklist:

- [x ] My change is being tested and reviewed against the Sparkle 2.x branch. New changes must be developed on the 2.x development branch first.

## Type of change
- [x ] My change is or requires a documentation or localization update

Hello there!
While using application baked with Sparkle framework I found some non-ideal Russian translations in the updater window.

Some of the strings are machine-translated and sound unnatural, some other have non-consistent word forms. I've fixed all of them and changed some of the strings accordingly.

### CODE REVIEW

**Review by vozersky — APPROVED** [review]

**Review by Snawoot — APPROVED** [review]

**Comment by zorgiepoo** [comment]
Thank you

**Comment by sc0rp10** [comment]
@zorgiepoo what do you think about backporting these strings into 1.x branch? Can you tag a release after I finish the merge?

**Comment by zorgiepoo** [comment]
Yes we can please create a PR for 1.x branch to expedite the process. Will need to back port #1943 too.

**Comment by sc0rp10** [comment]
@zorgiepoo I'm sorry, I'm the newbie in cocoapods. What target branch should I select as a target for my PR?

**Comment by zorgiepoo** [comment]
Handling it in #1949

**Pull request merged**
