### PR TITLE
Workaround for timing issue of termination detection.

### PR DESCRIPTION
**Pull request by fujisoft**
part of #1079
I have no problem with this patch. But I have no idea that 2sec-delay is enough for every configuration.

### CODE REVIEW

**Comment by pornel** [comment]
Why does this help? Do you have an idea what's causing the problem?

**Comment by fujisoft** [comment]
When the process is just dying, kill() will return zero. Then AutoUpdate.app wait kevent forever. This patch is a workaround for this problem.
I think that another solution is back to old "watch dog" version.

**Comment by pornel** [comment]
So the diagnosis is that the `kevent`-based watching is not reliable and sometimes doesn't see the app quit?

**Comment by fujisoft** [comment]
Maybe rarely. The code doesn't see the app quit. Only few users report this problem.
I am not sure which has the problem, kevent() and/or kill(). It is hard to reproduce the problem.

**Comment by pornel** [comment]
OK, let's give it a try

**Comment by fujisoft** [comment]
Thank you!
Here is quick diagnostic data from our beta testers.
case0: 3
case1: 18
case2(workaround code): 2
And, we have not received any report about update failure.

with the test code:
```
    if ([self terminated]) {
        if (self.completionBlock != nil) NSLog(@"DEBUG(case1)");
        [self invokeCompletionWithSuccess:YES];
    }
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        if ([self terminated]) {
            if (self.completionBlock != nil) NSLog(@"DEBUG(case2)");
            [self invokeCompletionWithSuccess:YES];
        }
    });
}

static void noteExitKQueueCallback(CFFileDescriptorRef file, CFOptionFlags __unused callBackTypes, void *info)
{
    struct kevent event;
    kevent(CFFileDescriptorGetNativeDescriptor(file), NULL, 0, &event, 1, NULL);
    
    TerminationListener *self = CFBridgingRelease(info);
    self.watchedTermination = YES;
    if (self.completionBlock != nil) NSLog(@"DEBUG(case0)");
    [self invokeCompletionWithSuccess:YES];
}

```

**Comment by cherpake** [comment]
Hi,

Sorry but this haven't solved the issue for me...
Updated to Sparkle 1.18.1 and still hitting this issue.
Please let me know if there is something I can do to help solve this issue.

default	17:14:28.512820 +0300	authd	Succeeded authorizing right 'system.privilege.admin' by client '/Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app' [78448] for authorization created by '/Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app' [78448] (13,0)
error	17:14:28.513915 +0300	Autoupdate	Failed to perform final installation Error: Error Domain=SUSparkleErrorDomain Code=4005 "Failed to execute package installer." UserInfo={NSLocalizedDescription=Failed to execute package installer., NSUnderlyingError=0x7fa65b42d100 {Error Domain=SUSparkleErrorDomain Code=4001 "Failed to run authorization tool /Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app/Contents/MacOS/fileop (error code -60008)." UserInfo={NSLocalizedDescription=Failed to run authorization tool /Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app/Contents/MacOS/fileop (error code -60008).}}}

**Comment by cherpake** [comment]
Hi,

This doesn't seem to fix this issue for me, let me know how I can help...

Here what I see in the console logs:
default	17:29:59.398541 +0300	authd	Succeeded authorizing right 'system.privilege.admin' by client '/Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app' [80442] for authorization created by '/Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app' [80442] (13,0)
error	17:29:59.399807 +0300	Autoupdate	Failed to perform final installation Error: Error Domain=SUSparkleErrorDomain Code=4005 "Failed to execute package installer." UserInfo={NSLocalizedDescription=Failed to execute package installer., NSUnderlyingError=0x7fd46a720590 {Error Domain=SUSparkleErrorDomain Code=4001 "Failed to run authorization tool /Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app/Contents/MacOS/fileop (error code -60008)." UserInfo={NSLocalizedDescription=Failed to run authorization tool /Users/cherpake/Library/Caches/com.cherpake.macrc.server/org.sparkle-project.Sparkle/Remote for Mac (Autoupdate).app/Contents/MacOS/fileop (error code -60008).}}}

**Pull request merged**
