### PR TITLE
update PR #1512 again to fix compilation issues

### PR DESCRIPTION
**Pull request by core-code**

### CODE REVIEW

**Comment by RobFog** [comment]
Three merge commits? Maybe try a rebase. Probably also makes sense to combine the other three commits into one.

**Comment by core-code** [comment]
i hate git. i can just delete my fork and create a new fork if you prefer a single commit ;)

**Comment by kornelski** [comment]
BTW: `git rebase -i origin/master` is the way to clean up commits. Also see interactive rebase in https://git-fork.com/

**Comment by kornelski** [comment]
BTW: `git rebase -i origin/master` is the way to clean up commits. Also see interactive rebase in https://git-fork.com/

**Pull request merged**
