### PR TITLE
More verbose error message when DSA keys don't match

### PR DESCRIPTION
**Pull request by pornel**
To help diagnosing problems like #562

### CODE REVIEW

**Comment by zorgiepoo** [comment]
Left a couple of comments. Also, I don't think an application has to be code signed with a certificate issued from Apple. A certificate from someone else, or self-signed, should be able to go through the validation code too.

**Comment by pornel** [comment]
> I don't think an application has to be code signed with a certificate issued from Apple

Do you mean the error messages should say code signing rather than apple code signing?

**Comment by zorgiepoo** [comment]
Yeah.

**Comment by pornel** [comment]
So in this case I've meant Apple's technology for Code Signing, as opposed to Sparkle's DSA way of signing code.

Do you have an idea how to call it to make it very clear that "code signing" is not the same as Sparkle's DSA signature?

**Comment by zorgiepoo** [comment]
I personally don't associate code signing with Sparkle's DSA signatures.. Technically speaking, Sparkle only signs downloadable archives, not code. One possibility is to associate Sparkle's DSA signatures with archives and code signing with apps?

Seems to look good otherwise.

**Pull request merged**
