### PR TITLE
Fix release note WebView's appearance in dark mode

### PR DESCRIPTION
**Pull request by Bi11**
Most changes are cherry-picked from PR #1280 and #1288.

### CODE REVIEW

**Comment by michelf** [comment]
Maybe you should consider also picking PR #1293 & #1294 and commit 45d27cc5d07191320e32bf1813e63232db54f247 (which solves issue #1307).

**Comment by michelf** [comment]
Oh, I see you're observing the window's appearance instead of the release note view's. That could make the other changes less necessary.

**Comment by Bi11** [comment]
Umm, yes. `NSWindowController.window` is a strong reference.

**Comment by kornelski** [comment]
Nice :)

**Pull request merged**
