### PR TITLE
Add ed25519 support to XPC branch

### PR DESCRIPTION
**Pull request by tonyarnold**
Please merge #1422 before this branch. 

This is presently a work in progress to bring forward the ed25519 changes from `master` to the XPC and UI separation branch.

### CODE REVIEW

**Comment by DivineDominion** [comment]
@tonyarnold What do we need to do to make this less a WIP branch and make it merge-able?

**Comment by tonyarnold** [comment]
@DivineDominion buy me a TARDIS and a Mac Pro? 

I need to find some time to finish moving the changes over. I've been quite busy is all.

**Comment by kornelski** [comment]
How's this going?

**Comment by tonyarnold** [comment]
Honestly, I've not had time to spend on this. I'll see what I can do in the next few days.

**Comment by belkadan** [comment]
I shoved through the framework side of this by looking at @kornelski's commits from 1.21.0, plus the work on SUSignatureVerifier.m and SUUpdateValidator.m since then. It would *definitely* need review from someone else, though.

https://github.com/belkadan/Sparkle/tree/feature/ed25519

**Comment by tonyarnold** [comment]
@belkadan want to open a PR from your end? Happy to manage this any which way (including just stepping out of the way), given how little time I've had to work on this.

**Comment by tonyarnold** [comment]
Oh, I'm also happy to help review 👍

**Comment by belkadan** [comment]
@kornelski, any opinions?

**Comment by belkadan** [comment]
Well, I opened #1553, and that way we can get started with review, at least. Happy to change to whatever process ends up best.

**Pull request merged**
