### PR TITLE
Updated Turkish Translations and XIB Layout Fixes

### PR DESCRIPTION
**Pull request by bitigchi**

### CODE REVIEW

**Comment by kornelski** [comment]
> "Install and Relaunch" = "Kur ve yeniden başlat";

This is a label on a button. Does Apple use lowercase words on multi-word buttons in Turkish?

**Comment by bitigchi** [comment]
Not really. In Turkish, general practice is to use lowercase letters for imperative cases, but Apple keeps them all uppercase anyway. Do you want to keep it consistent with the rest of the system?

**Comment by kornelski** [comment]
Yes, we try to blend in and follow whatever Apple is doing.

**Comment by bitigchi** [comment]
Fixed.

**Comment by kornelski** [comment]
I've merged it in fc3221c5d2ddedf443b0b46e2fe64efdefe32f2b

**Pull request closed without merging**
