### PR TITLE
SUFeedUrl generate appcast file extension

### PR DESCRIPTION
**Pull request by Neoster**
When the SUFeedURL extension is "php", replace filename.php with appcast.xml in generate_appcast

### CODE REVIEW

**Comment by kornelski** [comment]
Thanks for the PR. Please use deleteLastPathComponent and appendPathComponent instead of find'n'replace.

**Comment by Neoster** [comment]
@kornelski I did process your requested changes.

**Comment by kornelski** [comment]
The '*ing` methods don't modify the variable, but make a new value, which you're not using. So this code doesn't do anything now.

**Comment by Neoster** [comment]
Ok, I am sorry about that. I am not familiar with the Sparkle ecosystem yet, so I will figure out a way to test this. Will keep you posted.

**Comment by kornelski** [comment]
Thank you

**Pull request merged**
