### PR TITLE
Ask permission for automatically downloading and installing new updates

### LINKED ISSUE #2209: Add option to automatically download/install new updates in permission prompt
From discussion #2208, in the permission prompt I think we should consider adding a checkbox option that reflects `SUAutomaticallyUpdate` / `-setAutomaticallyDownloadsUpdates:` (i.e, an option to automatically download/install new updates).

Current permission prompt:
Screen Shot 2022-07-18 at 9 03 05 PM

### PR DESCRIPTION
**Pull request by zorgiepoo**
In the update permission prompt, we add an option/checkbox to allow the user to opt into (or out of) automatically downloading and installing updates:

Screenshot 2022-11-27 at 5 31 36 AM

Screenshot 2022-11-27 at 5 32 22 AM

The default on or off state of automatically downloading and installing updates is based on the value the developer sets for `SUAutomaticallyUpdate` key in their Info.plist. If this is not specified, the default value is off.

After the user responds to the prompt, the updater sets its `automaticallyDownloadsUpdates` property based on the user's response. If the user doesn't want automatic updates checks, we assume the user doesn't want automatic downloading too.

If `SUAllowsAutomaticUpdates` is specified to `NO` then this option and checkbox is hidden in this prompt. In this case, we ignore the response to the user automatically downloading and installing updates.

As usual if the developer overrides and specifies `SUEnableAutomaticChecks` in their Info.plist, this permission prompt does not show up and we also don't record the user's response to this option.

I tried to update many of the localizations based on us already translating a similar key: "Automatically download and install updates in the future". However for this key I wanted to remove "in the future" bit.

I didn't localize and gave up on:

* Chinese (main land)
* Chinese (Taiwan)
* Chinese (Hong Kong)
* Hungarian
* Japanese
* Korean
* Slovak
* Thai

Fixes #2209

## Misc Checklist

- [x] My change requires a documentation update on [Sparkle's website repository](https://github.com/sparkle-project/sparkle-project.github.io)
- [ ] My change requires changes to generate_appcast, generate_keys, or sign_update

Only bug fixes to regressions or security fixes are being backported to the 1.x (master) branch now. If you believe your change is significant enough to backport, please also create a separate pull request against the master branch.

## Testing

I tested and verified my change by using one or multiple of these methods:

- [x] Sparkle Test App
- [ ] Unit Tests
- [ ] My own app
- [ ] Other (please specify)

Tested the permission prompt with the test app in several different languages and tested that `automaticallyDownloadsUpdates` property on `SPUUpdater` is set (or not set) based on the user's response.

macOS version tested: 13.0.1 (22A400)

### CODE REVIEW

**Comment by zorgiepoo** [comment]
> I didn't localize and gave up on:
>
> * Chinese (main land)
> * Chinese (Taiwan)
> * Chinese (Hong Kong)
> * Hungarian
> * Japanese
> * Korean
> * Slovak
> * Thai

cc @Eitot @ososoio @ChiahongHong @kasimok @horcs @1024jp @chotiwat based on people that have added or updated relevant translations in the past and want to provide input on how `Automatically download and install updates` should be translated to one of the languages mentioned above.

**Comment by ChiahongHong** [comment]
Hello, @zorgiepoo 

For `"Automatically download and install updates"`, here are the corresponding Chinese localizations:

- [Chinese (zh_TW)](https://github.com/sparkle-project/Sparkle/blob/a6536ea8f1fbc2930bcab70384d97b83287bd62b/Sparkle/zh_TW.lproj/SUUpdateAlert.strings#L17) `"自動下載並安裝更新項目"`
- [Chinese (zh_HK)](https://github.com/sparkle-project/Sparkle/blob/a6536ea8f1fbc2930bcab70384d97b83287bd62b/Sparkle/zh_HK.lproj/SUUpdateAlert.strings#L17) `"自動下載並安裝更新"`
- [Chinese (zh_CN)](https://github.com/sparkle-project/Sparkle/blob/a6536ea8f1fbc2930bcab70384d97b83287bd62b/Sparkle/zh_CN.lproj/SUUpdateAlert.strings#L17) `"自动下载并安装更新"`

Thanks.

**Comment by chotiwat** [comment]
Thanks for asking. `Automatically download and install updates` in Thai should be `ดาวน์โหลดและติดตั้งอัพเดทโดยอัตโนมัติ`.

**Comment by zorgiepoo** [comment]
Thanks all.

**Pull request merged**
