### PR TITLE
Update app icon for Autoupdate.app (#347)

### PR DESCRIPTION
**Pull request by 1024jp**
ref. #347

Hey, I finished up the new app icon.

I've actually changed it quite a lot from the first draft ver, more than I expected.
The foreground and background colors were flipped in order to make it more like "inner process".
Furthermore, I even omitted the sparkle symbols I added. Now it looks super generic.

(I also can revert the sparkle symbols If you think it's better, as shown below.)

Good to merge or some tweak required?

### CODE REVIEW

**Comment by pornel** [comment]
Oh, it is nicer indeed! I think I slightly prefer the sparkly version. 

Have you experimented with using some yellow accents? As a homage to Sparkle's previous palette.

**Comment by 1024jp** [comment]
Ok, so, I've swaped images with the sparkly version.

> Have you experimented with using some yellow accents? As a homage to Sparkle's previous palette.

Yes actually. I've tried using yellow at first.
However, it didn't work well because the combination of blue and yellow is too showy for such a helper app. Considering that Sparkle will be built in another applications, IMO, the icon of Autoupdate.app should not disterb the atmosphere of client application.

**Comment by pornel** [comment]
Great. Thank you.

**Comment by RobFog** [comment]
Great improvement. The old icon always struck me as a bit odd.

**Comment by 1024jp** [comment]
Thanks for the merge 😃
I'm glad that my work will be used in this great framework.

**Comment by zorgiepoo** [comment]
Xcode gives warnings that "The app icon set "AppIcon" has 3 unassigned children" - does this need to be addressed?

**Comment by 1024jp** [comment]
@zorgiepoo 
Ops, I just forgot assign them in Xcode.
I've made a pull-request fixing it at #804.

**Pull request merged**
