### PR TITLE
Add delegate methods for pre-download and immediately post-failed-download.

### PR DESCRIPTION
**Pull request by vokal-isaac**
This enables modifying the download request (e.g., to add authentication credentials) and catching download-specific errors separately.

### CODE REVIEW

**Comment by jakepetroules** [comment]
:+1: 

@pornel?

**Comment by pornel** [comment]
Sure, why not?

**Comment by vokal-isaac** [comment]
Thanks.

Out of curiosity, is there a planned release cycle of some sort?

**Comment by pornel** [comment]
We don't have a fixed release cycle. If you'd like to use that change quickly I suggest testing version from master. We try to keep master stable.

**Comment by vokal-isaac** [comment]
I've been using master for the past several days and it does seem stable and completely usable from my perspective.  I was mostly curious because it's slightly cleaner to use a tagged version through Cocoapods than to use master, but not a problem at all.

Thanks!

**Pull request merged**
