### PR TITLE
Improve Unarchiver Tests

### PR DESCRIPTION
**Pull request by zorgiepoo**
* All supported compression formats are now tested including dmg, which
has a license agreement included
* The hash of the extracted directory is now checked, which encompasses
every file's existence, its contents, and its permissions.
* Re-written using Swift

---

Currently it's using Swift 2. Let me know if it'll have to use 1.2 instead, at the moment.

### CODE REVIEW

**Comment by pornel** [comment]
> OS X targets using Swift cannot be built against an SDK older than 10.10, but the effective SDK is 10.9.
** TEST FAILED **

**Comment by zorgiepoo** [comment]
Xcode for me says it's set at "No SDK (Latest OS X)" - I'm not extremely familiar with the build configurations to know what is supposed to change. Or if it's something you have to change on travis.

**Comment by pornel** [comment]
I think the Makefile is trying to run on all SDKs since 10.7: https://github.com/sparkle-project/Sparkle/blob/master/Makefile#L24

Try changing it to 10.10+

**Comment by jakepetroules** [comment]
> I think the Makefile is trying to run on all SDKs since 10.7: https://github.com/sparkle-project/Sparkle/blob/master/Makefile#L24

Yes, I did that because we claim to support Xcode 5+. Ideally I'd like to keep the project as a whole buildable with the 10.7 SDK, if we can think of a good way to easily exclude the tests from SDKs < 10.10.

**Comment by pornel** [comment]
In Build Settings for Sparkle Unit Tests target set SDK to 10.10?

**Comment by jakepetroules** [comment]
That won't work. I pushed something that should...

**Comment by jakepetroules** [comment]
> Currently it's using Swift 2. Let me know if it'll have to use 1.2 instead, at the moment.

We probably should wait to merge since that'll require Xcode 7. Might take Travis a while to support it, too.

**Comment by pornel** [comment]
OK, that 637eaae9c722774e84686b43c3f232e65340c593 makes more sense :)

**Comment by zorgiepoo** [comment]
Xcode 7 is now officially out, as well as Swift 2. Travis also can [support Xcode 7](http://blog.travis-ci.com/2015-09-09-xcode7-gm/) now. I think this is now or very close to being merge-able?

**Comment by pornel** [comment]
Can you update travis config file to enable xcode7?

**Comment by zorgiepoo** [comment]
Updated to use xcode7 and fixed CI building

**Comment by jakepetroules** [comment]
Just put SWIFT_OPTIMIZATION_LEVEL settings in the global Debug/Release files; no need to create specific ones for the ConfigUnitTest target.

**Comment by zorgiepoo** [comment]
I moved them into the global configs, although I'm not exactly sure how the unit test configs inherit from them.

**Pull request merged**
