### PR TITLE
Fixed appcast parsing issue

### PR DESCRIPTION
**Pull request by pornel**

### CODE REVIEW

**Comment by pornel** [comment]
Should disabling JS (#755) go into 1.14.0? Just in case I've based that on earlier commits

**Comment by zorgiepoo** [comment]
Looks good to me 👍. +1 for the unit test.

I don't see a downside of incorporating the JS change sooner than later. Although, I think we should address #731 soon too so maybe we ought to lump those together as far as security/incompatibility changes go.

**Comment by pornel** [comment]
1.13 has a bug in support for feedurl set by delegates, so I'd like to release a fix ASAP, without waiting for #731 to be implemented.

**Comment by zorgiepoo** [comment]
Sounds good.

**Pull request merged**
