### PR TITLE
Add preprocessor macro 'NDEBUG' to prevent  assertions failures on production build.

### PR DESCRIPTION
**Pull request by GetToSet**
Add preprocessor macro `NDEBUG` to prevent triggering assertions failures on production build.

According to man pages, unlike Foundation assertions, which are always disabled on release builds, C style `assert` should be removed by `NDEBUG` macro, which is not a default setup for Xcode build system.

## Checklist:

- [x] My change is being tested and reviewed against the Sparkle 2.x branch. New changes must be developed on the 2.x development branch first.
- [x] My change is being backported to master branch (Sparkle 1.x). Please create a separate pull request for 1.x, should it be backported. Note 1.x is feature frozen and is only taking bug fixes, localization updates, and critical OS adoption enhancements.
- [x] I have reviewed and commented my code, particularly in hard-to-understand areas.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] My change is or requires a documentation or localization update

## Testing

I tested and verified my change by using one or multiple of these methods:

- [x] Sparkle Test App
- [x] Unit Tests
- [x] My own app
- [ ] Other (please specify)

macOS version tested: 12.1 (21C52)

### CODE REVIEW

**Comment by zorgiepoo** [comment]
This sounds like a good change to make, although I'm not too concerned about our assert() usage here.

The CI build fails (it's supposed to post warnings, not fail, but that's a different issue) because additional analyzer/compiler warnings come up from this change. The `assert(false)` code was silencing the completion handler warnings about certain paths not being taken (which upon review should not be possible, hence the asserts).

>  /Users/runner/work/Sparkle/Sparkle/Sparkle/InstallerProgress/InstallerProgressAppController.m:245:9: warning: completion handler is never called when taking false branch [-Wcompletion-handler] if (applicationBundlePath != nil && !self.willTerminate) { ^ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Sparkle/InstallerProgress/InstallerProgressAppController.m:245:9: warning: completion handler is never called when taking false branch [-Wcompletion-handler] if (applicationBundlePath != nil && !self.willTerminate) { ^ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Autoupdate/SUUnarchiverNotifier.m:31:5: warning: completion handler is never used when taking false branch [-Wcompletion-handler] if (self != nil) { ^ 1 warning generated. 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Autoupdate/SUUnarchiverNotifier.m:31:5: warning: completion handler is never used when taking false branch [-Wcompletion-handler] if (self != nil) { ^ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Autoupdate/SUBinaryDeltaCreate.m:128:13: warning: unused variable 'sizeBack' [-Wunused-variable] ssize_t sizeBack = listxattr(ent->fts_path, buffer, (size_t)listSize, options); ^ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Autoupdate/SUBinaryDeltaCreate.m:128:13: warning: Value stored to 'sizeBack' during its initialization is never read [deadcode.DeadStores] ssize_t sizeBack = listxattr(ent->fts_path, buffer, (size_t)listSize, options); ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Sparkle/SUUpdatePermissionPrompt.m:68:5: warning: completion handler is never used when taking false branch [-Wcompletion-handler] if (self) ^ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUUIBasedUpdateDriver.m:42:5: warning: completion handler is never used when taking false branch [-Wcompletion-handler] if (self != nil) { ^ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUInstallerDriver.m:168:15: warning: unused variable 'installationType' [-Wunused-variable] NSString *installationType = self.updateItem.installationType; ^ 1 warning generated. 1 warning generated. 1 warning generated. error: the following command failed with exit code 0 but produced no further output CompileC /Users/runner/work/Sparkle/Sparkle/analyze/Build/Intermediates.noindex/Sparkle.build/Release/Sparkle.build/Objects-normal/arm64/SPUUIBasedUpdateDriver.o /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUUIBasedUpdateDriver.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Sparkle' from project 'Sparkle') /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUInstallerDriver.m:168:15: warning: unused variable 'installationType' [-Wunused-variable] NSString *installationType = self.updateItem.installationType; ^ 1 warning generated. 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUInstallerDriver.m:168:15: warning: Value stored to 'installationType' during its initialization is never read [deadcode.DeadStores] NSString *installationType = self.updateItem.installationType; ^~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 1 warning generated. /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUCoreBasedUpdateDriver.m:73:19: warning: Value stored to 'bundleIdentifier' during its initialization is never read [deadcode.DeadStores] NSString *bundleIdentifier = host.bundle.bundleIdentifier; ^~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 1 warning generated.

**Comment by zorgiepoo** [comment]
> According to man pages, unlike Foundation assertions, which are always disabled on release builds,

These must be controlled by `ENABLE_NS_ASSERTIONS` which we've the same issue here (always enabling it).

**Comment by zorgiepoo** [comment]
Actually taking a deeper look, I don't think we should disable asserts as they indicate the program is an unexpected state and something is seriously wrong if the program were to continue (any asserts we have are not like this should be updated). This has actually helped us before pinpoint invalid configurations that would have been harder to diagnosis if the asserts were disabled.

Except perhaps the bsdiff target where performance may be impacted. Disabling asserts in release builds is more of a policy decision rather than a bug.

**Comment by GetToSet** [comment]
> Except perhaps the bsdiff target where performance may be impacted. Disabling asserts in release builds is more of a policy decision rather than a bug.

I understand your concern, maybe I'll remove assertions on our private Sparkle build. BTY, would it be better to add `ENABLE_NS_ASSERTIONS` macro to allow Foundation assertions to be triggered for release build as well to make the behavior consistent? If so, I'll make another dedicated PR for this.

**Comment by zorgiepoo** [comment]
It's already on by default without an Xcode override, so it appears to be consistent.

**Pull request closed without merging**
